# -*- coding: utf-8 -*-
"""instruction scheduling full project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ufGgTjiB9oUAawUNFrJKWd_3HwQNcPi
"""

# training data generation and creating control flow flow graph

"""
Instruction Scheduling Project — Multi-Personality Data Generator & CFG Builder
-------------------------------------------------------------------------------

This script performs:
  1. Synthetic C++-like code generation with multiple "programmer personalities"
  2. Control Flow Graph (CFG) construction for each generated code
  3. Dataset creation (data.csv) containing:
         code_str | labels
     in the current working directory

Each function is carefully documented with detailed comments.
"""

import random
import csv
from typing import List, Tuple, Dict

# ---------------------------------------------------------------------
# Step 1: Personality-based code generation
# ---------------------------------------------------------------------

def _rand_var():
    """Return a random single-letter variable name."""
    return random.choice([chr(c) for c in range(ord("a"), ord("z") + 1)])


def _assign_statement(var: str = None, val: int = None) -> str:
    """Generate a single assignment statement like 'x = 4'."""
    if var is None:
        var = _rand_var()
    if val is None:
        val = random.randint(0, 5)
    return f"{var} = {val}"


def _if_block_chain(max_chain=3) -> Tuple[str, list[int]]:
    """
    Generate a random if–else-if–else block chain and corresponding labels.
    Labels represent whether each condition evaluates True (1) or False (0).
    """
    var = _rand_var()
    val = random.randint(0, 5)
    pre = f"{var} = {val}\n"
    chain_len = random.randint(1, max_chain)

    parts, labels = [], []
    for i in range(chain_len):
        c = random.randint(0, 5)
        op = random.choice(["<", ">", "==", "<=", ">="])
        cond = f"if({var} {op} {c})" if i == 0 else f"else if({var} {op} {c})"
        expr = f"{val} {op} {c}"
        try:
            label = 1 if eval(expr) else 0
        except Exception:
            label = 0
        labels.append(label)
        parts.append(cond + " {\n    " + _assign_statement() + "\n}")
    # Optional else block
    if random.choice([True, False]):
        parts.append("else {\n    " + _assign_statement() + "\n}")
    return pre + "\n".join(parts), labels


def _for_block() -> Tuple[str, int]:
    """Generate a small for-loop block and a binary label (loop executed or not)."""
    iter_count = random.randint(0, 3)
    loop = f"for(int i=0; i<{iter_count}; i++) {{\n    {_assign_statement()}\n}}"
    label = 1 if iter_count > 0 else 0
    return loop, label


# ---------------------------------------------------------------------
# Step 2: Personalities — define 4 programmer styles
# ---------------------------------------------------------------------

def _generate_personality_code(personality: str,
                               min_statements=3,
                               max_statements=7) -> Tuple[str, list[int]]:
    """
    Generate code influenced by a specific 'personality' (style).
    Each personality has its own statistical preferences.
    """
    stmts, labels = [], []

    if personality == "A":  # Compact coder
        choices = ["assign"] * 5 + ["if"] * 2 + ["for"]
    elif personality == "B":  # Verbose coder
        choices = ["assign"] * 3 + ["if"] * 3 + ["for"] * 2
    elif personality == "C":  # Experimental coder
        choices = ["assign"] * 2 + ["if"] * 3 + ["for"] * 3
    else:  # D — Structured coder (balanced)
        choices = ["assign"] * 4 + ["if"] * 2 + ["for"] * 2

    stmt_count = random.randint(min_statements, max_statements)
    for _ in range(stmt_count):
        choice = random.choice(choices)
        if choice == "assign":
            stmts.append(_assign_statement())
        elif choice == "if":
            chain, l = _if_block_chain()
            stmts.append(chain)
            labels.extend(l)
        else:
            loop, l = _for_block()
            stmts.append(loop)
            labels.append(l)

    stmts.append("END")  # terminal marker
    return "\n".join(stmts), labels


def generate_codes(n: int = 100,
                   personalities: List[str] = ["A", "B", "C", "D"]) -> Tuple[List[str], List[list[int]]]:
    """
    Generate 'n' random code samples by mixing multiple programmer personalities.
    Returns lists of (codes, labels).
    """
    codes, labels_list = [], []
    for _ in range(n):
        personality = random.choice(personalities)
        code, labels = _generate_personality_code(personality)
        codes.append(code)
        labels_list.append(labels)
    return codes, labels_list


# ---------------------------------------------------------------------
# Step 3: Control Flow Graph (CFG) Builder
# ---------------------------------------------------------------------

def build_cfg(code_str: str) -> Tuple[Dict[int, str], Dict[int, list[int]]]:
    """
    Build a simple control-flow-graph (CFG) from a C++-like code string.

    Each assignment or control structure (if-chain, for-loop) is a node.
    The adjacency list (edges) represents possible control transfers.
    """
    lines = [ln.strip() for ln in code_str.splitlines() if ln.strip() != ""]

    items = []
    i = 0
    while i < len(lines):
        ln = lines[i]
        # Handle if/else-if/else chains
        if ln.startswith("if(") or ln.startswith("else if(") or ln.startswith("else"):
            conds, bodies, has_else = [], [], False
            while i < len(lines) and (lines[i].startswith("if(")
                                      or lines[i].startswith("else if(")
                                      or lines[i].startswith("else")):
                cur = lines[i]
                if cur.startswith("else") and not cur.startswith("else if("):
                    j = i + 1
                    if j < len(lines) and lines[j].startswith("{"): j += 1
                    body = []
                    while j < len(lines) and '}' not in lines[j]:
                        body.append(lines[j]); j += 1
                    if j < len(lines) and '}' in lines[j]: j += 1
                    bodies.append("\n".join(body) if body else "<EMPTY>")
                    has_else = True
                    i = j; break
                else:
                    conds.append(cur)
                    j = i + 1
                    if j < len(lines) and lines[j].startswith("{"): j += 1
                    body = []
                    while j < len(lines) and '}' not in lines[j]:
                        body.append(lines[j]); j += 1
                    if j < len(lines) and '}' in lines[j]: j += 1
                    bodies.append("\n".join(body) if body else "<EMPTY>")
                    i = j
            items.append({"type": "if_chain", "conds": conds,
                          "bodies": bodies, "has_else": has_else})
            continue

        # Handle for-loops
        if ln.startswith("for("):
            header = ln
            j = i + 1
            if j < len(lines) and lines[j].startswith("{"): j += 1
            body = []
            while j < len(lines) and '}' not in lines[j]:
                body.append(lines[j]); j += 1
            if j < len(lines) and '}' in lines[j]: j += 1
            items.append({"type": "for", "header": header,
                          "body": "\n".join(body) if body else "<EMPTY>"})
            i = j; continue

        # Plain assignment
        items.append({"type": "assign", "text": ln})
        i += 1

    # Convert items → nodes and edges
    nodes, start_indices = [], []
    for it in items:
        start_indices.append(len(nodes))
        if it["type"] == "assign":
            nodes.append(it["text"])
        elif it["type"] == "for":
            nodes += [it["header"], it["body"]]
        elif it["type"] == "if_chain":
            for cond, body in zip(it["conds"], it["bodies"]):
                nodes += [cond, body]
            if it.get("has_else") and len(it["bodies"]) > len(it["conds"]):
                nodes.append(it["bodies"][-1])

    edges = {i: [] for i in range(len(nodes))}

    # Edge creation logic (main control flow)
    for idx, it in enumerate(items):
        start = start_indices[idx]
        exit_idx = start_indices[idx + 1] if idx + 1 < len(start_indices) else len(nodes)

        if it["type"] == "assign":
            if exit_idx < len(nodes):
                edges[start].append(exit_idx)

        elif it["type"] == "for":
            hdr, body = start, start + 1
            edges[hdr] = [body, exit_idx] if exit_idx < len(nodes) else [body]
            edges[body] = [hdr]  # loop back

        elif it["type"] == "if_chain":
            pairs = len(it["conds"])
            for k in range(pairs):
                cond, body = start + 2*k, start + 2*k + 1
                nxt = start + 2*(k+1) if k + 1 < pairs else (
                    start + 2*pairs if it.get("has_else") else exit_idx)
                edges[cond] = [body, nxt] if nxt < len(nodes) else [body]
                edges[body] = [exit_idx] if exit_idx < len(nodes) else []
            if it.get("has_else"):
                else_idx = start + 2*pairs
                edges[else_idx] = [exit_idx] if exit_idx < len(nodes) else []

    node_dict = {i: nodes[i] for i in range(len(nodes))}
    for k in edges:
        edges[k] = [x for x in edges[k] if x < len(nodes)]
    return node_dict, edges


# ---------------------------------------------------------------------
# Step 4: Dataset creation — saving to CSV
# ---------------------------------------------------------------------

def save_dataset_to_csv(codes: List[str], labels_list: List[list[int]], filename="data.csv"):
    """
    Save generated dataset to CSV.
    Each row: [code_str, labels]
    """
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["code_str", "labels"])
        for code, labels in zip(codes, labels_list):
            writer.writerow([code, labels])
    print(f"✅ Dataset saved to {filename} (total {len(codes)} samples)")


# ---------------------------------------------------------------------
# Step 5: Main demo — end-to-end generation and saving
# ---------------------------------------------------------------------

if __name__ == "__main__":
    # Generate 100 random samples across 4 programmer personalities
    codes, labels_list = generate_codes(n=100)

    # Build CFG for the first sample (demo only)
    sample_code = codes[0]
    node_dict, adj_list = build_cfg(sample_code)

    print("Sample Generated Code:\n----------------------")
    print(sample_code, "\n")

    print("Node Dictionary:")
    for k, v in node_dict.items():
        print(f"  {k}: {v}")
    print("\nAdjacency List:")
    for k, v in adj_list.items():
        print(f"  {k} -> {v}")

    # Save dataset
    save_dataset_to_csv(codes, labels_list)

import pandas as pd

df=pd.read_csv('data.csv')

print(df.head())

df.loc[0, "code_str"]